exports.seed = async function(knex) {
  await knex('calendar_events').del()
  await knex('user_notice').del()
  await knex('chain_of_command').del()
  await knex('calendar_users').del()
  await knex('event_type').del()
  await knex('calendar_teams').del()
  await knex('notice_type').del()
  await knex('notice_status').del()
  await knex('user_type').del()
  await knex('ranks').del()
  await knex.raw('TRUNCATE TABLE ranks RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE user_type RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE notice_status RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE notice_type RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE calendar_teams RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE event_type RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE calendar_users RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE chain_of_command RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE user_notice RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE calendar_events RESTART IDENTITY CASCADE')
}